name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs surveyapp
    - name: Deploy to GH Pages
      run: |
        echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
        echo FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
        echo FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} >> .env
        echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> .env
        echo FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
        echo FIREBASE_MESSASING_SENDER_ID=${{ secrets.FIREBASE_MESSASING_SENDER_ID }} >> .env
        git config --global user.email ${{ secrets.PERSONAL_GITHUB_EMAIL }}
        git config --global user.name ${{ secrets.PERSONAL_GITHUB_USERNAME }}
        git remote set-url origin https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ secrets.PERSONAL_GITHUB_USERNAME }}/survey-app.git
        npm run deploy