name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: npm run deploy
      - name: Updating Deploy
        run: |
          git config --global user.email ${{ secrets.PERSONAL_GITHUB_EMAIL }}
          git config --global user.name ${{ secrets.PERSONAL_GITHUB_USERNAME }}
          git remote set-url origin https://${{ secrets.PERSONAL_GITHUB_TOKEN }}>@github.com/${{ secrets.PERSONAL_GITHUB_USERNAME }}/survey-app.git
          npm run deploy